In [3]:
import numpy as np

scalar = 5
scalar_arr = np.array([5])

print(scalar_arr)

vector = np.array([1,2,3])
another_vector = np.array([4,5,6])

print(vector)
print(np.dot(vector, another_vector))

matrix = np.array([[1,2,3], [4,5,6]]) # 2 by 3

print(matrix)
print(matrix.T)

another_matrix = np.array([[4,5,6], [1,2,3]]) # 2 by 3
yet_another_matrix = np.array([[4,5], [1,2], [7,8]]) # 3 by 2 (needed for dot product)

print(matrix + another_matrix)
print(matrix - another_matrix)
print(matrix * another_matrix)
print(np.dot(matrix, yet_another_matrix))


tensor = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(tensor)

[5]
[1 2 3]
32
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[5 7 9]
 [5 7 9]]
[[-3 -3 -3]
 [ 3  3  3]]
[[ 4 10 18]
 [ 4 10 18]]
[[27 33]
 [63 78]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
# problem

# lets say happiness quotient can be calulated as 300 - 50d where d = number of work days

# for 5 people, d = 10 20 30 15 25

# programming solution

d = np.array([10,20,30,40,50])

for i in range(5):
    print(300 - 5 * d[i])

# linear algebra solution

d = np.array([[1, 10],[1, 20],[1, 30],[1, 40],[1, 50]])

equation = np.array([[300], [-5]])

print(np.dot(d, equation))
 

250
200
150
100
50
[[250]
 [200]
 [150]
 [100]
 [ 50]]
