In [2]:
import numpy as np

scalar = 5
scalar_arr = np.array([5])

print(scalar_arr)

vector = np.array([1,2,3])
another_vector = np.array([4,5,6])

print(vector)
print(np.dot(vector, another_vector))

matrix = np.array([[1,2,3], [4,5,6]]) # 2 by 3

print(matrix)
print(matrix.T)

another_matrix = np.array([[4,5,6], [1,2,3]]) # 2 by 3
yet_another_matrix = np.array([[4,5], [1,2], [7,8]]) # 3 by 2 (needed for dot product)

print(matrix + another_matrix)
print(matrix - another_matrix)
print(matrix * another_matrix)
print(np.dot(matrix, yet_another_matrix))


tensor = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(tensor)

[5]
[1 2 3]
32
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[5 7 9]
 [5 7 9]]
[[-3 -3 -3]
 [ 3  3  3]]
[[ 4 10 18]
 [ 4 10 18]]
[[27 33]
 [63 78]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
# problem

# lets say happiness quotient can be calulated as 300 - 50d where d = number of work days

# for 5 people, d = 10 20 30 15 25

# programming solution

d = np.array([10,20,30,40,50])

for i in range(5):
    print(300 - 5 * d[i])

# linear algebra solution

d = np.array([[1, 10],[1, 20],[1, 30],[1, 40],[1, 50]])

equation = np.array([[300], [-5]])

print(np.dot(d, equation))
 

250
200
150
100
50
[[250]
 [200]
 [150]
 [100]
 [ 50]]


In [9]:
# features are age(years), weight(kg) and height(cm)

features = np.array([[34, 56, 190],[14, 70, 140],[24, 53, 169],[53, 98, 170],[94, 66, 173],[33, 86, 181],[23, 46, 170]])
# suppose we know that model dictates 0.03*age + 0.04*weight + 0.05*height + 1 = outcomes
weights = np.array([0.03, 0.04, 0.05])
outcomes = np.dot(features, weights) + 1
print(outcomes)

# sometimes data may be feature wise instead of row wise
features = np.array([[34, 14, 24, 53, 94, 33, 23], [56, 70, 53, 98, 66, 86, 46], [190, 140, 169, 170, 173, 181, 170]])
# then you need to use transpose
outcomes = np.dot(features.T, weights) + 1
print(outcomes)

[13.76 11.22 12.29 15.01 15.11 14.48 12.03]
[13.76 11.22 12.29 15.01 15.11 14.48 12.03]
